---
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2024 Lewes Technology Consulting, LLC

- name: Install Cerebro RPM
  yum:
    name: '{{ cerebro_rpm_url }}'
    state: present
  tags: sof-elk_cerebro

- name: Set Cerebro directory permissions
  file:
    dest: '/usr/share/cerebro'
    recurse: true
    owner: cerebro
    group: cerebro
  tags: sof-elk_cerebro

- name: Open firewall ports
  firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
  notify: reload firewalld
  tags: sof-elk_cerebro

- name: Enable and start Cerebro service
  ansible.builtin.systemd_service:
    name: cerebro
    enabled: true
    state: started
  tags: sof-elk_cerebro
