---
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2024 Lewes Technology Consulting, LLC

- name: Wait for Elasticsearch to be ready
  ansible.builtin.command: '/usr/local/sof-elk/supporting-scripts/wait_for_es.sh'
  tags: sof-elk_finalize

- name: Run the post-merge script, which also loads all dashboards
  ansible.builtin.command: '/usr/local/sof-elk/supporting-scripts/post_merge.sh'
  tags: sof-elk_finalize

- name: Restart Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
  tags: sof-elk_finalize
